# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/p:OutputPath="$(build.artifactStagingDirectory)"'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dropper'
    publishLocation: 'Container'

- task: CmdLine@2
  inputs:
    script: |
      git clone https://djrj4ch7wvwv3mkm6kbythgzgcs3k3mfsfwgquydu3zd2oeaibna@dev.azure.com/PrivaSec/PrivaTools/_git/PrivaTools

      git checkout master
      
      copy "$(Build.ArtifactStagingDirectory)" Test      
    
      cd Test
      
      git add .
      
      git commit -m "Add line numbered code."
      
      git tag $(Build.BuildNumber)
      
      git push https://djrj4ch7wvwv3mkm6kbythgzgcs3k3mfsfwgquydu3zd2oeaibna@dev.azure.com/PrivaSec/PrivaTools/_git/PrivaTools master 
