# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/p:OutputPath="$(build.artifactStagingDirectory)"'
    configuration: '$(buildConfiguration)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dropper'
    publishLocation: 'Container'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: '0x10f2c'
    repositoryName: 'PrivasecRED/Azure-Pipelines-Artifacts'
    action: 'create'
    target: '$(Build.BuildNumber)'
    tagSource: 'userSpecifiedTag'
    tag: 'Release'
    title: 'Seatbelt'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'Release'
    addChangeLog: false